name: Creer la release

on:
  workflow_run:
    workflows:
      - Créer un tag
    types:
      - completed


permissions:
  contents: write
jobs:
  change_version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Modifier la version du package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: 'Modifier la version'
        run: |
            git fetch --tags
            TAG=$(git describe --tags --abbrev=0)
            git config user.name "gitops"
            git config user.email "gitops@gitops.com"
            yq eval -i '.version = "$TAG"' pyproject.toml
            git add pyproject.toml
            git commit -m "Updating version for this package:
            Branch  : ${{ github.event.workflow_run.head_branch }}
            Author  : ${{github.event.workflow_run.actor}}
            Message : Mis à jour de la version"
            git push
  create_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Creer la release
    runs-on: ubuntu-24.04
    needs: change_version
    permissions:
      contents: write # Requis pour autoriser la création de la release
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      
      - name: Create GitHub Release Native
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          gh release create "$TAG" \
          --title "Dockersmart $TAG" \
          --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authentification